server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melroyr/spring-proactive-architecture-config
          default-label: main
          skipSslValidation: true