eureka:
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname:
      localhost
      
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
