server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accounts
          uri: lb://account-service
          predicates:
            - Path=/banking/account/**

        - id: banking
          uri: lb://banking-service
          predicates:
            - Path=/banking/process/**

        - id: reporting
          uri: lb://reporting-service
          predicates:
            - Path=/banking/report/**

        - id: users
          uri: lb://user-service
          predicates:
            - Path=/banking/fraud/**
springdoc:
  swagger-ui:
    urls:
      - name: employee
        url: /v3/api-docs/employee
      - name: department
        url: /v3/api-docs/department
      - name: organization
        url: /v3/api-docs/organization

management:
  tracing:
    sampling:
      probability: 1.0